name: haweyati
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  in_app_review:


  # Internationalization (i18n) Support.
  flutter_localizations:
    sdk: flutter
  intl:

  share:
  path_provider:
  firebase_dynamic_links:

  # Firebase Cloud Notifications (FCM)
#  firebase_messaging:

  # Location and Maps Plugins
  geocoder:
  location:
  google_maps_flutter:
  flutter_google_places:
  google_maps_webservice:

  # Storage related Plugins
  hive:
  hive_flutter:
  shared_preferences:

  # Plugins for Social Authentication
  firebase_auth: ^0.20.1

  # Payment related Plugins
  stripe_payment:
  flutter_credit_card:

  # Network related Plugins
  dio:
  retrofit:
  json_annotation:
  json_serializable:

  # Inter-App communication Plugins
  url_launcher:
  image_picker:
  app_settings:
  webview_flutter:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
#  hypertrack_plugin:
  pretty_dio_logger:
  myfatoorah_flutter:

  # Application packages
  haweyati_client_data_models:
    path: ../haweyati-client_data-models

dependency_overrides:
  intl: ^0.16.0
  image_picker: 0.6.7+22

dev_dependencies:
  build_runner: ^1.10.4
  hive_generator: ^0.8.1
  retrofit_generator:
  flutter_native_splash:

  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/map-icons/
    - assets/images/
    - assets/images/country-flags/
    - assets/images/home-page/
    - assets/images/features/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato.ttf

    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica.ttf

#flutter_native_splash:
#  image: assets/images/haweyati_logo.png
#  color: "ffffff"
#  fill: true
#  android_disable_fullscreen: true

